### PR TITLE
Created generic script for directing tasks among chiplets

### PR DESCRIPTION
**Pull request by raytsou**
Unified the tasks_redirect scripts to dynamically obtain core P#'s using lstopo-no-graphics and parsed with Perl. Will now exit if only one CCX is detected. Can edit variable $LAUNCHER to use script without lutris. Also cleaned up some of the logging.

Tested successfully on 5900x and 2700x, both running Ubuntu 22

### CODE REVIEW

**Comment by AdelKS** [comment]
Hello! Thank you very much for this contribution. I'll have a look at it asap ! Also, there's a simpler approach using systemd slices but the weird thing about it when I tried it is that I couldn't revert the system to its original state without two sets. I'll share that with you if you want to have a look. We would still need your code to figure out how to split the CPU

**Comment by raytsou** [comment]
I'd be happy to look at that, I'm not familiar with systemd slices / cgroups but a quick look around online says that's probably a better tool for the job compared to this echo stuff. Is there a branch you can share with me or do you just want to drop it attached to a comment below?

Also I came across another tool named [cset](https://manpages.ubuntu.com/manpages/trusty/man1/cset-shield.1.html) that basically does the same echo'ing stuff as in your bash script but is written in python. It might be useful, but would introduce a pre-req of having it installed.

**Comment by AdelKS** [comment]
Sorry for taking so much time to get to it, I forgot about it and it fell down my list of things to do, I really need to try it just once to confirm it works on my machine. the systemd slices approach will come later, I'll open an issue about it. Thanks again!

**Comment by AdelKS** [comment]
Works great on my 5950X ! thanks !

**Pull request merged**
